### PR TITLE
Add rrd

### PR DESCRIPTION
**Pull request by aremazeilles**
I think this one is redy to be uploaded.
The docker image is uploaded.
They are using emg as input, but no PI is generated, only an image for now.
I think (hope) this is ok.

You will tell me...

### CODE REVIEW

**Comment by aremazeilles** [comment]
There are two protocols by the way: one defined in `rrd_walk_stair`, and `rrd_walk_slope`.

**Comment by alfonsotecnalia** [comment]
The lenght of visualization_tool field in pi table should be extended. I do not have permissions for that. Adrian should do it.

**Comment by aremazeilles** [comment]
cool cool cool.
Maybe we can on friday revise all items to check what is uploaded and wat is missing.

**Comment by alfonsotecnalia** [comment]
I do not know why I have closed this. The yaml has been uploaded to the DB and the images are in the S3 instance. However the docker image has not been tested. Do not know how to reopen this. Maybe it is better to open another pull request for the docker image.

**Comment by aremazeilles** [comment]
Well now that the branch is merged, it is complex to move backwards. So I guess this is why you cannot reopen it. Let´s create a new issue for this then

**Pull request merged**
