### PR TITLE
add protocols

### PR DESCRIPTION
**Pull request by aremazeilles**

### CODE REVIEW

**Comment by aremazeilles** [comment]
FYI @alfonsotecnalia , based on the email discussion, I added the scenario of waterloo stair based on the pdf file.

I will add progressively the others here. But if you want to make an early check if the current format is ok...
I will inform you when all will have been uplaoded

**Comment by aremazeilles** [comment]
Ping @alfonsotecnalia , all new protocols added.... might take a bit of time for you to integrate into the database?

**Comment by alfonsotecnalia** [comment]
Expect to do it between today and Monday. But it will depend on Altran. I have no access to the DB at this moment. I suppose they are updating something

**Comment by alfonsotecnalia** [comment]
I still do not have access to the database. I can not upload anything without permissions. Adrian/Altran are aware of this.

**Comment by alfonsotecnalia** [comment]
Protocols have been updated and checked in a local DB. However access to the main DB need to be granted in order to upload information to it.

**Comment by alfonsotecnalia** [comment]
Uploaded. Images will be available once the script in the AWS instace is run

**Pull request merged**
