### PR TITLE
Insert uhei

### PR DESCRIPTION
**Pull request by aremazeilles**
Felix gave me two protocols, sit to stand, and flat grounf walking.

Would it be possible to embed them into the system, even if the algorithm is not ready yet?

### CODE REVIEW

**Comment by alfonsotecnalia** [comment]
A user should be created before but the we is down. I will proceed as sson as the web is up.

**Comment by alfonsotecnalia** [comment]
There is already an scenario called "Sit to stand" (coming from BENCH). Do we want to overwrite its description or consider it as other scenario? If first, which description (see below) suits better? If latest, another name should be put in UHEI yaml. 

BENCH: Sit-to-stand (STS) is an important task for assessing dynamic balance and lower limb coordination and has a significant clinical relevance. STS is important also for assessing the performance of wearable lower-limb exoskeletons for assistance and humanoid robots that imitate human movements. These protocols and the associated PIs aim at the the assessment and benchmarking of the sit-to-stand gesture in intact and impaired individuals, in human/exoskeleton systems and in humanoid robots.

UHEI: Assessment of the motion capability of the robot in the lateral plane

**Comment by aremazeilles** [comment]
@flxalr will confirm, but I assume UHEI sut-to-stand is dedicated to humanoid, while the one from BENCH as a broader scope. So we would like to have both.

**Comment by alfonsotecnalia** [comment]
ok

**Comment by flxalr** [comment]
Yes, I think both are exclusive for the targeted systems - exo and humanoid with (probably) two different instrumented chairs.

**Comment by alfonsotecnalia** [comment]
Done. The protocols are in the website. Image will be available one S3 script is run.

**Pull request merged**
