### PR TITLE
Add dysturbance

### PR DESCRIPTION
**Pull request by aremazeilles**
Adding Disturbance description.

I will update the original repo to indicate possible input files.

**Cautious** : dysturbance is already present:

```yaml
* Integrated: 4 protocols, **NO PDF**
  * [Dysturbance -Reaction to Impulsive Disturbance](https://platform.eurobench2020.eu/protocols/info/39)
  * [Dysturbance - Reaction to Sinusoidal Force Disturbance](https://platform.eurobench2020.eu/protocols/info/40)
  * [Dysturbance - Reaction to Sinusoidal displacement Disturbance](https://platform.eurobench2020.eu/protocols/info/41)
  * [Dysturbance - Reaction to external Quasistatic Disturbance](https://platform.eurobench2020.eu/protocols/info/40)
```

**BUT** , they dediced to split the last protocol into 2: Reaction to external Quasistatic Force Disturbance (line 230), and Reaction to external Quasistatic Displacement Disturbance (line 295)

I assigned the current numbers to the 3 first (39, 40 and 41). but I did not set anything for the the last one, which is for now in 40.

I adjusted the Pi listing as we mentioned (factorize the Pi names, even though the vector output may differ from a protocol to another), but I did not update the excel sheet. Hope this is ok.

Will ping you as soon as I have updated the code readme with docker command as example.

### CODE REVIEW

**Comment by aremazeilles** [comment]
Example of docker code completed in https://github.com/CentroEPiaggio/dysturbance/tree/extend_doc/Dysturbance_Pi#docker-usage
ready for revision

**Comment by alfonsotecnalia** [comment]
Absorbed.yaml and Stability_margin.yaml indicates the units of the different elements between []. This is not compatible with yaml. Examples:

```
type: vector 
label: [E_perc, Force Max [N], Normalized Max Force [N], Max (Initial) Energy [J], Normalized Max (Initial) Energy [J], Initial Angle [deg], Added Mass [Kg], Impulse [Ns], Absorbed Energy [J]] 
value: [1, 135.56, 148.158, 0.385994, 0.48941, -7.86431, 3.5, 0.781942, 0.385994]
```

**Comment by aremazeilles** [comment]
I will propose change to handle the unit differently. 
For the filename. does it work as is ? To know if it is critical to request that change

**Comment by aremazeilles** [comment]
> Input files cond_XXX_testbed.yaml and really condition files. Change the name to condition_XXX.yaml

The filename is right now of the form: `subject_1_cond_2101000000_testbed.yaml` 
Would `subject_1_condition_2101000000.yaml` be acceptable?

At the computation level, it does not change anything. I guess this is how their acquisition software keep the data. I could propose either to change their acquisition software, or to add in the code documentation a section on preparing data for Eurobench computation, in which this filename change could be requested

**Comment by aremazeilles** [comment]
With [ae02c1c](https://github.com/eurobench/eurobench_protocol/pull/66/commits/ae02c1cf901e13fdf209661d9a6bf685b7c45e90) I upgrade the docker version, and now the label string should be compatible.

For the condition file name, I mentioned it in to the dysturbance team. But I think it could be left as an indication for using the online version, so that the information should be fine as is from our perspective

**Pull request merged**
