### PR TITLE
adjust yaml content

### PR DESCRIPTION
**Pull request by aremazeilles**
Adjustng the yaml to the excel file. See #28

### CODE REVIEW

**Comment by aremazeilles** [comment]
I actualized the docker image. By the way, I realized that I don't know how to update the fork without making a merge commit. The only solution I find ok is to push through my pc to the fork branch. But if you know a way to do it directly through the Github interface directly, I would be glad to learn it.

**Comment by Enri2077** [comment]
See correction to the excel file in commit https://github.com/eurobench/eurobench_protocol/pull/28/commits/a38355eb9566dd660c1b5d84702c3951572209b9

**Comment by aremazeilles** [comment]
Now it should fine

**Comment by aremazeilles** [comment]
@alfonsotecnalia Could you double check the status of beast on the server?

From what I see, the [eurobench clone](https://github.com/eurobench/pi_madrob_beast) is up to date with the official repo, and the second release 2.0.0 is based on the latest commit.

**Comment by aremazeilles** [comment]
Made a commit to handle the conflict with man branch

**Comment by aremazeilles** [comment]
ping @alfonsotecnalia

**Comment by alfonsotecnalia** [comment]
beast uploaded to eurobench website. it works

**Comment by Enri2077** [comment]
> beast uploaded to eurobench website. it works

Nice to know @alfonsotecnalia , is there a way to see the website? Thank you

**Comment by aremazeilles** [comment]
It is there: https://15.237.22.1/home
Your protocol is there: https://15.237.22.1/protocols/info/21

Actually I see there is no reference to the github code, where the manual is added. Maybe something to add in the information displayed?

**Pull request merged**
