### PR TITLE
Updated BEAST description

### PR DESCRIPTION
**Pull request by Enri2077**
Updated:
* Controlled variables
* Protocol description
* Performance Indicators
* PI Algo (shorter description of one algorithm to compute all PIs)
* fixed typos

### CODE REVIEW

**Comment by aremazeilles** [comment]
To complete this, I should update the associated yaml file, and then update the docker image associated to that protocol.

I'll start loooking at the yaml content. and inform here.

**Comment by aremazeilles** [comment]
@Enri2077 may I ask you to check if your changes are well reflected in https://github.com/eurobench/eurobench_protocol/pull/29 ?

2 comments: 
* I would suggest changeing the protocol name to be "BEAST: operating wheeled device", and move the second line withint the protocol definition.
* Is there a particular reason for having one PI per time to checkpoint? Would it make sense to put them all within a vector, having one entry per checkpoint? Not to be done now, just to check.

@alfonsotecnalia The docker image would still need to be updated, I will have a look at it, and inform here once a new version is created.

**Comment by Enri2077** [comment]
I noticed a problem here: https://github.com/eurobench/eurobench_protocol/pull/29/files#diff-33b61da82a93cfff092a4f6cfe39a31de2446bad0d33249fd33cc32c811dab2dR45 The description refers to MADROB. I'll correct it in the excel file and do another commit.

**Comment by Enri2077** [comment]
> @Enri2077 may I ask you to check if your changes are well reflected in #29 ?
> 
> 2 comments:
> 
> * I would suggest changeing the protocol name to be "BEAST: operating wheeled device", and move the second line withint the protocol definition.

Done: https://github.com/eurobench/eurobench_protocol/pull/28/commits/a38355eb9566dd660c1b5d84702c3951572209b9, see cells C14 and C15, as well as the updated condition variable description in cell C26.

> * Is there a particular reason for having one PI per time to checkpoint? Would it make sense to put them all within a vector, having one entry per checkpoint? Not to be done now, just to check.

No other reason than the fact I forgot about this possibility! I'll change it to a vector if it is necessary.

> @alfonsotecnalia The docker image would still need to be updated, I will have a look at it, and inform here once a new version is created.

**Pull request merged**
