### PR TITLE
Update uhei metrics

### PR DESCRIPTION
**Pull request by aremazeilles**
UHEI algorithm is to be inserted into several humanoid protocols. 
I start with the slope algorithm, as it generates a significant number of metrics.

As the db is out of date, I don't know whether you can check anything locally?

### CODE REVIEW

**Comment by alfonsotecnalia** [comment]
I could do some checks. I miss the docker image and the command in the yaml. I would need also some input files to test. Is there any docker image in dockerhub? Is the command the one in the repo or other one? Can I use the test files in the repo?

**Comment by alfonsotecnalia** [comment]
Is [this ](https://hub.docker.com/r/eurobenchtest/eb_hum_bench) the docker image?

**Comment by alfonsotecnalia** [comment]
The modified docker command is:
````
docker run --rm -v $PWD/tests/reemc_conf:/conf -v $PWD/tests/input:/in -v $PWD/tests/output:/out i3sa /conf/robot.yaml /in/subject_001_cond_001_run_001_wrench.csv /in/2021_02_19/14/1/pos.csv /in/input/2021_02_19/14/1/vel.csv /in/input/2021_02_19/14/1/acc.csv /in/input/2021_02_19/14/1/trq.csv /in/input/2021_02_19/14/1/ftl.csv /in/2021_02_19/14/1/ftr.csv /out
````
I think it will not work as it has two "input" folders (`conf, `in`). The part of the subfolders will not work either. I will create  for the test a unique input folder with all the files.

**Comment by aremazeilles** [comment]
you have the good image. 
On the docker call, we suggested to place the files in conf in the same repository.
Then the docker call i slightly wrong: it should be:

```
docker run --rm -v $PWD/tests/reemc_conf:/conf -v $PWD/tests/input/2021_02_19/14/1:/in -v $PWD/output:/out i3sa:latest run_i3sa /conf/robot.yaml /conf/reemc.lua /in/pos.csv  /in/vel.csv /in/acc.csv /in/trq.csv /in/ftl.csv /in/ftr.csv /in/gaitEvents.yaml /out
```

And if you place the robot.yaml and reemc.lua in the same folder, all would be in /in

**Comment by alfonsotecnalia** [comment]
'_' added to the name of some PIs because the output files are generated that way.
Mismatch between output type (vector) and type of value (scalar) solved by means of the pi_manager.

**Comment by alfonsotecnalia** [comment]
Locally tested. Waiting for the correction of the DDBB to upload to the platform

**Pull request merged**
