### PR TITLE
add: insert uhei metric references

### LINKED ISSUE #64: handle humanoid script
According to Felix, several humanoid protocols should be handled using their algorithm.

The algorithm is fully described in [uhei_flat.yaml](https://github.com/eurobench/eurobench_protocol/blob/main/data/uhei_flat.yaml), and it should apply also to: uhei_sts, uhei_slope, waterloo_stairs, waterloo_pcik, iit_treadmill, iit_inclined.

Should I copy then the algorithm and all associated metrics in the related yaml files ?

ping @alfonsotecnalia

### PR DESCRIPTION
**Pull request by aremazeilles**
fix #64

### CODE REVIEW

**Comment by alfonsotecnalia** [comment]
I do not find a gaitEvents.yaml file in https://gitlab.com/orb-benchmarking/eb_hum_bench/-/tree/master/tests/input and it is specified as an input for the algorithm.

**Comment by aremazeilles** [comment]
https://gitlab.com/orb-benchmarking/eb_hum_bench/-/tree/master/tests/input/2021_02_19/14/1

An example of command is added here: https://github.com/eurobench/eb_hum_bench#usage

**Comment by alfonsotecnalia** [comment]
Really? It is the only file in the whole bunch of data provided. What about the other folders? Why they do not have that file?

**Comment by alfonsotecnalia** [comment]
By the way. In the algorithm it is specified robot_model.lua and reemc.lua provided. Just to take it into account

**Comment by aremazeilles** [comment]
phone call

**Pull request merged**
